const data = {
  products: [
    {
      name: 'Deepak',
      slug:"deepak-product",
      category: 'human',
      image: '/images/pic1.jpg',
      price: 24500,
      brand: 'gora',
      numReviews: 2450,
      countInStock: 20,
      rating: 4.5,
      description: 'This is best in my app',
    },
    {
      name: 'vivek',
      slug:"vivek-product",
      category: 'human',
      image: '/images/pic2.jpg',
      price: 245,
      brand: 'gora',
      numReviews: 245000,
      countInStock: 2,
      rating: 4.5,
      description: 'This is best in my app',
    },
    {
      name: 'Dog',
      slug:"dog-product",
      category: 'animal',
      image: '/images/pic3.jpg',
      price: 24540,
      brand: 'gora',
      numReviews: 240,
      countInStock: 200,
      rating: 4.5,
      description: 'This is best in my app',
    },
    {
      name: 'Dogomak',
      slug:"dogomak-product",
      category: 'animal',
      image: '/images/pic3.jpg',
      price: 241,
      brand: 'black',
      numReviews: 2450,
      countInStock: 20,
      rating: 3,
      description: 'This is best in my app',
    },
    {
      name: 'handi',
      slug:"handi-product",
      category: 'puspa',
      image: '/images/pic2.jpg',
      price: 200,
      brand: 'ranja',
      numReviews: 2450,
      countInStock: 2,
      rating: 3.5,
      description: 'This is best in my app',
    },
  ],
};

export default data;
